"""«Академия гида»: как стать гидом, правила, лайфхаки и шпаргалки по объектам.

Факты собраны в сентябре 2026 из источников, указанных у каждой карточки.
Расстояния — ориентировочные, по данным туристических источников.
"""

# Платный въезд с 1.09.2026 (0,7 МРП за легковую, иностранцам ×2, оплата через Halyk).
FEE_SOURCE = ("inaktau.kz — платный въезд с 1 сентября 2026",
              "https://www.inaktau.kz/news/4141912/platnyj-vezd-i-novye-tarify-cto-izmenitsa-dla-turistov-v-mangistau-s-sentabra")
UNESCO_SOURCE = ("Times of Central Asia — UNESCO, июль 2026",
                 "https://timesca.com/unesco-adds-mangystau-rock-mosques-to-world-heritage-list/")

GENERAL = {
"ru": {
 "steps": [
  ("Язык", "Для свободного рассказа нужен уровень не ниже B2. Выучите «туристический» словарь: геология, архитектура, религия, техника безопасности. Репетируйте рассказ вслух — по 3–5 минут на каждую точку маршрута."),
  ("Знание маршрутов", "Съездите 3–5 раз ассистентом с опытным гидом. Записывайте, где остановки, где туалет, где связь, сколько ехать между точками."),
  ("Оформление", "С 1 августа 2026 действуют правила деятельности гидов (приказ Министра туризма и спорта от 15.07.2026): нужно гражданство РК и уведомление о начале деятельности через портал elicense.kz, гиды вносятся в государственный реестр."),
  ("Первая помощь", "Пройдите курс первой помощи и возите аптечку. Ближайшая больница может быть в 150+ км."),
  ("Профиль на площадке", "Укажите только те языки, на которых реально ведёте группу, отметьте объекты, которые знаете. Первые 5 заказов с хорошими отзывами переводят вас из «Новичка» в «Опытные»."),
 ],
 "rules": [
  "Письменно сообщите туристам особенности маршрута, местные правила и возможные опасности — не позднее чем за 3 календарных дня до поездки.",
  "О чрезвычайном происшествии сообщите уполномоченным органам в течение 1 рабочего дня.",
  "Экскурсия длится не более 24 часов; для опасных маршрутов нужно информированное согласие туриста.",
 ],
 "tips": [
  "Сезон — апрель–май и сентябрь–октябрь. Летом жара, зимой сильный ветер и заморозки.",
  "Заправьтесь и купите воду в Актау или Жанаозене: дальше магазинов и заправок почти нет.",
  "Связь на Устюрте нестабильна — заранее скачайте офлайн-карты и сообщите кому-то маршрут и время возвращения.",
  "Не заезжайте на соры (солончаки): под сухой коркой — топь. 31 мая 2026 семья туристов из Великобритании больше суток провела в солончаке у Тузбайыра.",
  "После дождя грунтовки из глины становятся непроходимыми: в феврале 2026 у Бозжыры ночью застряла машина с 6 туристами, а 27 апреля — два туристических автобуса, около 50 человек.",
  "С 1 сентября 2026 въезд на Бозжыру, Тузбайыр, Кызылкуп и Бокты платный: 0,7 МРП (3 028 ₸) за легковую машину, иностранцам — вдвое дороже, оплата через приложение Halyk. У иностранцев Halyk обычно нет — оплатите заранее сами.",
  "Солнцезащитные очки обязательны: белые скалы и соль отражают яркий свет даже весной.",
 ],
 "etiquette": [
  "В подземные мечети — закрытые плечи и колени, женщинам — платок. Говорить тихо, не шуметь.",
  "Паломников фотографировать только с разрешения. Предупредите группу заранее.",
  "Объясните туристам, почему места святые: это живые места паломничества, а не только памятники.",
 ],
},
"en": {
 "steps": [
  ("Language", "You need at least B2 to tell stories fluently. Learn the tour vocabulary: geology, architecture, religion, safety. Rehearse out loud — 3–5 minutes per stop on the route."),
  ("Know the routes", "Ride along 3–5 times as an assistant to an experienced guide. Note stops, toilets, where there is mobile signal and driving times between sites."),
  ("Registration", "Guide activity rules apply from 1 August 2026 (order of the Minister of Tourism and Sports of 15 July 2026): Kazakhstan citizenship and a notice of starting activity via elicense.kz are required; guides are entered in the state register."),
  ("First aid", "Take a first-aid course and carry a kit. The nearest hospital may be 150+ km away."),
  ("Your profile", "List only the languages you can really lead a group in and tick the sites you know. Your first 5 bookings with good reviews move you from Newcomer to Experienced."),
 ],
 "rules": [
  "Give travelers written information about the route, local rules and possible dangers no later than 3 calendar days before the trip.",
  "Report an emergency to the authorities within 1 working day.",
  "An excursion lasts no more than 24 hours; dangerous routes require the traveler's informed consent.",
 ],
 "tips": [
  "Season: April–May and September–October. Summers are hot, winters bring strong winds and frost.",
  "Refuel and buy water in Aktau or Zhanaozen — there are almost no shops or fuel stations further on.",
  "Mobile signal on the Ustyurt is unreliable — download offline maps and tell someone your route and return time.",
  "Never drive onto a sor (salt flat): under the dry crust there is a bog. On 31 May 2026 a family from the UK spent over a day stuck in a salt flat near Tuzbair.",
  "After rain, clay dirt roads become impassable: in February 2026 a car with 6 tourists got stuck overnight near Bozzhyra, and on 27 April two tour buses with about 50 people.",
  "Since 1 September 2026 entry to Bozzhyra, Tuzbair, Kyzylkup and Bokty is paid: 0.7 MCI (3,028 ₸) per car, double for foreigners, paid via the Halyk app. Foreigners rarely have Halyk — pay in advance yourself.",
  "Sunglasses are a must: white cliffs and salt reflect bright light even in spring.",
 ],
 "etiquette": [
  "For underground mosques: covered shoulders and knees, a headscarf for women. Speak quietly.",
  "Photograph pilgrims only with permission. Brief the group in advance.",
  "Explain why these places are sacred: they are living pilgrimage sites, not just monuments.",
 ],
},
"kk": {
 "steps": [
  ("Тіл", "Еркін әңгімелеу үшін кемінде B2 деңгейі керек. Туристік сөздікті үйреніңіз: геология, сәулет, дін, қауіпсіздік. Әр аялдамаға 3–5 минуттық әңгімені дауыстап жаттықтырыңыз."),
  ("Маршруттарды білу", "Тәжірибелі гидке көмекші ретінде 3–5 рет барыңыз. Аялдамаларды, дәретхананы, байланыс бар жерлерді және нысандар арасындағы жол уақытын жазып алыңыз."),
  ("Ресімдеу", "2026 жылғы 1 тамыздан бастап гидтер қызметінің қағидалары күшіне енді (Туризм және спорт министрінің 15.07.2026 бұйрығы): ҚР азаматтығы және elicense.kz порталы арқылы қызметті бастау туралы хабарлама қажет, гидтер мемлекеттік тізілімге енгізіледі."),
  ("Алғашқы көмек", "Алғашқы көмек курсынан өтіп, дәрі қобдишасын алып жүріңіз. Жақын аурухана 150+ км жерде болуы мүмкін."),
  ("Платформадағы профиль", "Тек топты шынымен жүргізе алатын тілдерді көрсетіп, білетін нысандарды белгілеңіз. Жақсы пікірлі алғашқы 5 тапсырыс сізді «Жаңадан бастаушыдан» «Тәжірибеліге» ауыстырады."),
 ],
 "rules": [
  "Туристерге маршрут ерекшеліктерін, жергілікті ережелерді және ықтимал қауіптерді сапардан кемінде 3 күнтізбелік күн бұрын жазбаша хабарлаңыз.",
  "Төтенше оқиға туралы уәкілетті органдарға 1 жұмыс күні ішінде хабарлаңыз.",
  "Экскурсия 24 сағаттан аспайды; қауіпті маршруттарға туристің хабардар келісімі қажет.",
 ],
 "tips": [
  "Маусым — сәуір–мамыр және қыркүйек–қазан. Жазда ыстық, қыста қатты жел мен үсік.",
  "Жанармай мен суды Ақтауда немесе Жаңаөзенде алыңыз: әрі қарай дүкен мен жанармай бекеті жоқтың қасы.",
  "Үстіртте байланыс тұрақсыз — офлайн карталарды алдын ала жүктеп, маршрут пен оралу уақытын біреуге айтыңыз.",
  "Сорларға кірмеңіз: құрғақ қыртыстың астында батпақ бар. 2026 жылғы 31 мамырда Ұлыбританиядан келген турист отбасы Тұзбайыр маңындағы сорда бір тәуліктен астам қалып қойды.",
  "Жаңбырдан кейін саз топырақты жолдар өтпейтін болады: 2026 жылғы ақпанда Бозжыра маңында 6 турист мінген көлік түнде балшыққа батып қалды, ал 27 сәуірде шамамен 50 адам мінген екі туристік автобус батты.",
  "2026 жылғы 1 қыркүйектен Бозжыра, Тұзбайыр, Қызылқұп және Боктыға кіру ақылы: жеңіл көлікке 0,7 АЕК (3 028 ₸), шетелдіктерге екі есе қымбат, Halyk қосымшасы арқылы төленеді. Шетелдіктерде Halyk әдетте болмайды — алдын ала өзіңіз төлеңіз.",
  "Күннен қорғайтын көзілдірік міндетті: ақ жартастар мен тұз көктемде де жарықты қатты шағылыстырады.",
 ],
 "etiquette": [
  "Жерасты мешіттеріне — иық пен тізе жабық, әйелдерге орамал. Ақырын сөйлеңіз.",
  "Зиярат етушілерді тек рұқсатпен суретке түсіріңіз. Топқа алдын ала ескертіңіз.",
  "Туристерге бұл жерлердің неге киелі екенін түсіндіріңіз: бұл тек ескерткіш емес, тірі зиярат орындары.",
 ],
},
}

RULES_SOURCE = ("zakon.kz — правила для гидов, 22.07.2026",
                "https://www.zakon.kz/pravo/6525570-dlya-gidov-i-ekskursovodov-utverdili-pravila-raboty.html")
INCIDENT_SOURCES = [
    ("zakon.kz — британские туристы в степи, 31.05.2026",
     "https://www.zakon.kz/proisshestviia/6519771-britanskie-turisty-okazalis-v-lovushke-v-stepi-mangistau.html"),
    ("inform.kz — два автобуса в грязи у Бозжыры, 27.04.2026",
     "https://www.inform.kz/ru/spasateli-vitashili-dva-avtobusa-s-turistami-iz-gryazi-u-bozzhiri-32d98d"),
]
READ_GENERAL = [
    ("Visit Mangystau — официальный туристический портал", "https://visitmangystau.kz/"),
    ("Сакральные места Мангистау — интерактивная карта", "https://mangystau.inmap.kz/"),
    ("Мангистауский историко-краеведческий музей", "https://www.muzey.kz/ru/mangystau/monuments"),
    ("UNESCO — Rock Mosques and Associated Sacred Sites of Mangystau", "https://whc.unesco.org/en/list/1760"),
    ("Википедия — Мангистауская область", "https://ru.wikipedia.org/wiki/Мангистауская_область"),
]

# Фразы для групп: английский и китайский (китайского гида сейчас не хватает сильнее всего).
PHRASES = [
    ("Welcome to Mangystau!", "欢迎来到曼格斯套！", "Huānyíng láidào Màngésītào!", "Добро пожаловать в Мангистау!", "Маңғыстауға қош келдіңіз!"),
    ("Please follow me.", "请跟我来。", "Qǐng gēn wǒ lái.", "Пожалуйста, за мной.", "Маған еріңіздер."),
    ("Please stay with the group.", "请不要离开团队。", "Qǐng bú yào líkāi tuánduì.", "Не отходите от группы.", "Топтан алыстамаңыздар."),
    ("Drink water often.", "请多喝水。", "Qǐng duō hē shuǐ.", "Чаще пейте воду.", "Суды жиі ішіңіздер."),
    ("Please be careful here.", "这里请注意安全。", "Zhèlǐ qǐng zhùyì ānquán.", "Здесь осторожно.", "Мұнда абай болыңыздар."),
    ("We leave in 15 minutes.", "我们十五分钟后出发。", "Wǒmen shíwǔ fēnzhōng hòu chūfā.", "Выезжаем через 15 минут.", "15 минуттан кейін жолға шығамыз."),
    ("This is a sacred place, please be quiet.", "这是圣地，请保持安静。", "Zhè shì shèngdì, qǐng bǎochí ānjìng.", "Это святое место, пожалуйста, тише.", "Бұл киелі орын, тыныштық сақтаңыздар."),
    ("Photos are allowed here.", "这里可以拍照。", "Zhèlǐ kěyǐ pāizhào.", "Здесь можно фотографировать.", "Мұнда суретке түсіруге болады."),
]


def _site(unesco=False, fee=False, sources=(), terms=(), ru=None, en=None, kk=None, draft=False):
    return {"unesco": unesco, "fee": fee, "sources": list(sources), "terms": list(terms),
            "ru": ru, "en": en, "kk": kk, "draft": draft}


def _t(tagline, tell, how, tips=(), safety=()):
    return {"tagline": tagline, "tell": list(tell), "how": list(how), "tips": list(tips), "safety": list(safety)}


W = "https://ru.wikipedia.org/wiki/"

SITES = {
"bozjyra": _site(
  fee=True,
  sources=[("welcome.kz — Урочище Бозжира", "https://welcome.kz/ru/info-cities/mangystau/bozzhira-tract"),
           ("zakon.kz — как добраться до Бозжыры", "https://www.zakon.kz/stati/6492862-dykhanie-vetra-i-tishina-vekov-kak-dobratsya-do-velichestvennoy-bozzhyry.html"),
           ("Википедия — Устюрт", W + "Устюрт")],
  terms=[("outlier / butte", "останец", "қалдық тау"), ("escarpment (chink)", "чинк, обрыв плато", "шың, жарқабақ"),
         ("plateau", "плато", "үстірт"), ("viewpoint", "смотровая площадка", "көру алаңы")],
  ru=_t("Цепочка останцов на дне каньона у западного чинка плато Устюрт — визитная карточка Мангистау.",
        ["У входа в долину стоят два останца — «клыки» высотой около 200 метров.",
         "Устюрт — пустынное плато площадью около 200 тыс. км² на территории Казахстана, Туркменистана и Узбекистана. Название от тюркского üst — «верхняя сторона».",
         "На Устюрте живёт устюртский муфлон: считался исчезнувшим, а осенью 2018 года его снова заметили с дрона на территории Казахстана."],
        ["≈270 км на восток от Актау по асфальту через Жанаозен и посёлок Узень (от Жанаозена около 150 км).",
         "Между тремя смотровыми площадками — ещё около 60 км грунтовки среднего качества: только внедорожник.",
         "Сезон — весна и осень: в это время здесь десятки туристов в день, многие остаются с ночёвкой."],
        ["Рассвет и закат над «клыками» — главные кадры тура: планируйте выезд так, чтобы успеть к ним.",
         "Въезд платный с 1 сентября 2026 — оплатите заранее."],
        ["После дождя в долину не спускайтесь: глинистые дороги раскисают — в 2026 году здесь застревали и легковая машина, и два туристических автобуса."]),
  en=_t("A chain of buttes on a canyon floor below the western escarpment of the Ustyurt Plateau — the signature view of Mangystau.",
        ["Two buttes at the valley entrance, the “fangs”, rise about 200 metres.",
         "The Ustyurt is a desert plateau of about 200,000 km² across Kazakhstan, Turkmenistan and Uzbekistan. The name comes from Turkic üst, “the upper side”.",
         "The Ustyurt mouflon, once thought extinct, was spotted again by a drone in Kazakhstan in autumn 2018."],
        ["≈270 km east of Aktau on asphalt via Zhanaozen and Uzen (about 150 km from Zhanaozen).",
         "About 60 more km of average dirt road between the three viewpoints — 4×4 only.",
         "Season: spring and autumn, when dozens of tourists come daily and many stay overnight."],
        ["Sunrise and sunset over the “fangs” are the key shots of the tour — time your departure for them.",
         "Entry is paid since 1 September 2026 — pay in advance."],
        ["Do not descend into the valley after rain: clay roads turn to mud — in 2026 both a car and two tour buses got stuck here."]),
  kk=_t("Үстірт үстіртінің батыс шыңы түбіндегі шатқалдағы қалдық таулар тізбегі — Маңғыстаудың басты көрінісі.",
        ["Алқапқа кіре берісте биіктігі шамамен 200 метр болатын екі қалдық тау — «азу тістер» тұр.",
         "Үстірт — Қазақстан, Түрікменстан және Өзбекстан аумағындағы шамамен 200 мың км² шөлді үстірт. Атауы түркінің üst — «жоғарғы жақ» сөзінен.",
         "Жойылып кетті деп есептелген үстірт арқары 2018 жылдың күзінде Қазақстан аумағында дронмен қайта байқалды."],
        ["Ақтаудан шығысқа қарай Жаңаөзен мен Өзен кенті арқылы асфальтпен ≈270 км (Жаңаөзеннен шамамен 150 км).",
         "Үш көру алаңы арасында тағы шамамен 60 км орташа сапалы топырақ жол — тек жол талғамайтын көлік.",
         "Маусым — көктем мен күз: бұл кезде күніне ондаған турист келіп, көбі түнеп қалады."],
        ["«Азу тістердің» үстіндегі таң мен күн батуы — турдың басты кадрлары: жолға соған үлгеретіндей шығыңыз.",
         "2026 жылғы 1 қыркүйектен кіру ақылы — алдын ала төлеңіз."],
        ["Жаңбырдан кейін алқапқа түспеңіз: саз жолдар батпаққа айналады — 2026 жылы мұнда жеңіл көлік те, екі туристік автобус та батып қалды."]),
),
"tuzbair": _site(
  fee=True,
  sources=[("Orexca — солончак Тузбаир", "https://www.orexca.com/rus/kazakhstan/mangystau/tuzbair.htm"),
           ("Kazakhstan.travel — сор Тузбаир", "https://kazakhstan.travel/tourist-spot/ru/273/sor-tuzbair")],
  terms=[("salt flat", "солончак, сор", "сор"), ("mirage", "мираж", "сағым"), ("chalk cliffs", "меловые скалы", "бор жартастар"),
         ("natural arch", "природная арка", "табиғи арка")],
  ru=_t("Белая соляная равнина под меловыми скалами Устюрта — место миражей и природной арки.",
        ["Солончак тянется примерно на 15 × 4 км; в жаркий день над ним возникают миражи — иллюзия озера.",
         "Скалы над сором высотой около 60 метров покрыты узорами, которые миллионы лет создавали ветер и вода.",
         "Местная достопримечательность — меловая «Арка», образовавшаяся из-за обрушения и размыва соседних скал."],
        ["≈270 км на северо-восток от Актау; последние 40 км — хорошая грунтовка с перепадами высот.",
         "Лучшие месяцы — апрель, май, сентябрь и октябрь."],
        ["По сору можно гулять босиком или в резиновых сапогах — туристы это любят.",
         "Воду и еду берите из Актау."],
        ["Не заезжайте на машине вглубь сора: корка выглядит твёрдой, но под ней топь. В мае 2026 спасатели больше суток вытаскивали здесь машину с семьёй туристов.",
         "Очки от солнца обязательны: соль и белые скалы слепят."]),
  en=_t("A white salt plain below the chalk cliffs of the Ustyurt — a place of mirages and a natural arch.",
        ["The salt flat stretches about 15 × 4 km; on hot days mirages appear above it — the illusion of a lake.",
         "The cliffs above the sor, about 60 m high, are carved into patterns shaped by wind and water over millions of years.",
         "A local highlight is the chalk “Arch”, formed when neighbouring rocks collapsed and eroded."],
        ["≈270 km north-east of Aktau; the last 40 km are a good dirt road with elevation changes.",
         "Best months: April, May, September and October."],
        ["Guests love walking on the sor barefoot or in rubber boots.",
         "Bring water and food from Aktau."],
        ["Never drive deep onto the sor: the crust looks solid, but there is a bog beneath. In May 2026 rescuers spent over a day pulling out a car with a tourist family here.",
         "Sunglasses are a must: the salt and white cliffs are blinding."]),
  kk=_t("Үстірттің бор жартастары астындағы ақ тұзды жазық — сағым мен табиғи арка орны.",
        ["Сор шамамен 15 × 4 км-ге созылады; ыстық күні оның үстінде сағым — көл елесі пайда болады.",
         "Сордың үстіндегі биіктігі шамамен 60 метр жартастарды миллиондаған жыл бойы жел мен су өрнектеген.",
         "Жергілікті көрікті жер — көршілес жартастардың опырылып, шайылуынан пайда болған бор «Арка»."],
        ["Ақтаудан солтүстік-шығысқа қарай ≈270 км; соңғы 40 км — биіктік өзгерістері бар жақсы топырақ жол.",
         "Ең қолайлы айлар — сәуір, мамыр, қыркүйек және қазан."],
        ["Сордың үстімен жалаңаяқ немесе резеңке етікпен жүруге болады — туристерге бұл ұнайды.",
         "Су мен тамақты Ақтаудан алыңыз."],
        ["Сордың ішіне көлікпен кірмеңіз: қыртыс қатты көрінеді, бірақ астында батпақ. 2026 жылғы мамырда құтқарушылар мұнда турист отбасы мінген көлікті бір тәуліктен астам шығарды.",
         "Күн көзілдірігі міндетті: тұз бен ақ жартастар көзді қарықтырады."]),
),
"sherkala": _site(
  sources=[("Википедия — Шеркала", W + "Шеркала")],
  terms=[("lone mountain", "одиночная гора", "жалғыз тау"), ("concretion", "конкреция", "конкреция"),
         ("caravan route", "караванный путь", "керуен жолы"), ("spring", "родник", "бұлақ")],
  ru=_t("Одиночная гора «Львиная крепость»: с одной стороны — юрта, с другой — спящий лев.",
        ["Название — от персидского «Шир-кала», «Крепость льва».",
         "С одной стороны гора похожа на шатёр белой юрты, с другой — на льва, положившего голову на лапы.",
         "Шеркала — местная святыня. По поверью, желание, загаданное перед тем, как обойти гору кругом, обязательно сбудется.",
         "Вокруг горы — шарообразные конкреции; в расколотых видны следы ракушек и рыб.",
         "Рядом — родник Акмыш и следы древнего поселения на караванном пути из Бухары на север."],
        ["≈94 км на северо-восток от Актау, 18 км от села Шетпе."],
        ["Обойти гору с желанием — лучший интерактив для группы, займите на это время в программе.",
         "Покажите группе расколотые конкреции с отпечатками — это наглядная история о древнем море."],
        ["Склоны отвесные, в горе много пещер — не отпускайте туристов лазать без присмотра."]),
  en=_t("A lone mountain called the “Lion's Fortress”: a yurt from one side, a sleeping lion from the other.",
        ["The name comes from Persian “Shir-kala”, the “Lion's Fortress”.",
         "From one side the mountain looks like a white yurt, from the other like a lion resting its head on its paws.",
         "Sherkala is a local sacred place: legend says a wish made before walking around the mountain will come true.",
         "Spherical concretions lie around the mountain; broken ones show imprints of shells and fish.",
         "Nearby are the Akmysh spring and traces of an ancient settlement on the caravan route from Bukhara to the north."],
        ["≈94 km north-east of Aktau, 18 km from Shetpe village."],
        ["Walking around the mountain with a wish is the best group activity — plan time for it.",
         "Show broken concretions with imprints — a vivid story about the ancient sea."],
        ["The slopes are sheer and there are many caves — do not let guests climb unsupervised."]),
  kk=_t("«Арыстан қорғаны» атты жалғыз тау: бір жағынан — киіз үй, екінші жағынан — ұйықтап жатқан арыстан.",
        ["Атауы парсының «Шир-қала» — «Арыстан қорғаны» сөзінен.",
         "Бір жағынан тау ақ киіз үйдің шатырына, екінші жағынан басын табанына қойған арыстанға ұқсайды.",
         "Шерқала — жергілікті киелі орын. Сенім бойынша тауды айналып шықпас бұрын тілек тілесең, ол орындалады.",
         "Тау айналасында шар тәрізді конкрециялар жатыр; сынғандарында бақалшақ пен балық іздері көрінеді.",
         "Жанында — Ақмыш бұлағы және Бұхарадан солтүстікке баратын керуен жолындағы ежелгі қоныстың іздері."],
        ["Ақтаудан солтүстік-шығысқа қарай ≈94 км, Шетпе ауылынан 18 км."],
        ["Тілек тілеп тауды айналу — топқа арналған ең жақсы белсенділік, бағдарламада уақыт бөліңіз.",
         "Іздері бар сынған конкрецияларды көрсетіңіз — ежелгі теңіз туралы көрнекі әңгіме."],
        ["Беткейлері тік, тауда үңгірлер көп — туристерді бақылаусыз өрмелетпеңіз."]),
),
"torysh": _site(
  sources=[("Википедия — Торыш", W + "Торыш")],
  terms=[("concretion", "конкреция", "конкреция"), ("Tethys Ocean", "океан Тетис", "Тетис мұхиты"),
         ("sediment", "отложения", "шөгінділер")],
  ru=_t("«Долина шаров»: каменные шары до 4 метров, выросшие на дне древнего океана Тетис.",
        ["Шары — это конкреции диаметром от 10–15 см до 4 метров.",
         "Им 40–60 миллионов лет: они образовались на дне древнего океана Тетис.",
         "Урочище лежит на западной оконечности хребта Западный Каратау."],
        ["≈150 км на север от Актау, 17,5 км на восток от села Таушык."],
        ["Дайте группе масштаб: поставьте человека рядом с самым большим шаром для фото.",
         "Удобно совмещать с Шеркалой в один день."],
        []),
  en=_t("The “Valley of Balls”: stone spheres up to 4 metres that grew on the floor of the ancient Tethys Ocean.",
        ["The balls are concretions from 10–15 cm up to 4 metres across.",
         "They are 40–60 million years old and formed on the floor of the ancient Tethys Ocean.",
         "The site lies at the western tip of the Western Karatau ridge."],
        ["≈150 km north of Aktau, 17.5 km east of Taushyk village."],
        ["Give the group a sense of scale: place a person next to the biggest ball for a photo.",
         "Easy to combine with Sherkala in one day."],
        []),
  kk=_t("«Шарлар алқабы»: ежелгі Тетис мұхитының түбінде өскен диаметрі 4 метрге дейінгі тас шарлар.",
        ["Шарлар — диаметрі 10–15 см-ден 4 метрге дейінгі конкрециялар.",
         "Олардың жасы 40–60 миллион жыл: ежелгі Тетис мұхитының түбінде пайда болған.",
         "Шатқал Батыс Қаратау жотасының батыс шетінде орналасқан."],
        ["Ақтаудан солтүстікке қарай ≈150 км, Таушық ауылынан шығысқа қарай 17,5 км."],
        ["Топқа масштабты сезіндіріңіз: суретке ең үлкен шардың қасына адамды тұрғызыңыз.",
         "Шерқаламен бір күнде біріктіру ыңғайлы."],
        []),
),
"bokty": _site(
  fee=True,
  sources=[("welcome.kz — гора Бокты", "https://welcome.kz/ru/info-cities/mangystau/bokty-peak")],
  terms=[("pyramid-shaped mountain", "гора-пирамида", "пирамида тәрізді тау"), ("chalk", "мел", "бор")],
  ru=_t("Природная пирамида высотой около 165 метров посреди полосатых меловых холмов.",
        ["Высота горы — около 165 метров; по форме это почти правильная пирамида, созданная природой.",
         "Рядом — холмы из слоёв белого и красного мела, местность Кызылкуп."],
        ["Ближайший город — Жанаозен, около 90 км.", "Обычно входит в один маршрут с Кызылкупом и Бозжырой."],
        ["Въезд платный с 1 сентября 2026."],
        []),
  en=_t("A natural pyramid about 165 metres high among striped chalk hills.",
        ["The mountain is about 165 m high — an almost perfect pyramid made by nature.",
         "Nearby are hills of white and red chalk layers, the Kyzylkup area."],
        ["The nearest town is Zhanaozen, about 90 km away.", "Usually combined with Kyzylkup and Bozzhyra in one route."],
        ["Entry is paid since 1 September 2026."],
        []),
  kk=_t("Жолақ бор төбелер арасындағы биіктігі шамамен 165 метр табиғи пирамида.",
        ["Таудың биіктігі шамамен 165 метр — табиғат жасаған дерлік дұрыс пирамида.",
         "Жанында — ақ және қызыл бор қабаттарынан тұратын төбелер, Қызылқұп жері."],
        ["Ең жақын қала — Жаңаөзен, шамамен 90 км.", "Әдетте Қызылқұп және Бозжырамен бір маршрутқа кіреді."],
        ["2026 жылғы 1 қыркүйектен кіру ақылы."],
        []),
),
"kyzylkup": _site(
  fee=True,
  sources=[("welcome.kz — урочище Кызылкуп", "https://welcome.kz/ru/info-cities/mangystau/urochishhe-kyizyilkup")],
  terms=[("layers / strata", "слои", "қабаттар"), ("Mesozoic era", "мезозойская эра", "мезозой заманы")],
  ru=_t("«Тирамису» — полосатые холмы красного, розового и белого цвета.",
        ["Слои красного, коричневого и розового цвета напоминают итальянский десерт — отсюда прозвище «Тирамису».",
         "Возраст слоёв относят к мезозойской эре."],
        ["≈240 км от Актау, рядом с горой Бокты."],
        ["Лучший свет — вечером, когда слои становятся контрастнее.", "Въезд платный с 1 сентября 2026."],
        []),
  en=_t("“Tiramisu” — striped hills of red, pink and white.",
        ["Red, brown and pink layers resemble the Italian dessert — hence the nickname “Tiramisu”.",
         "The layers date from the Mesozoic era."],
        ["≈240 km from Aktau, next to Mount Bokty."],
        ["Best light is in the evening, when the layers look most contrasting.", "Entry is paid since 1 September 2026."],
        []),
  kk=_t("«Тирамису» — қызыл, қызғылт және ақ түсті жолақ төбелер.",
        ["Қызыл, қоңыр және қызғылт қабаттар итальян десертіне ұқсайды — «Тирамису» деген атауы осыдан.",
         "Қабаттардың жасы мезозой заманына жатады."],
        ["Ақтаудан ≈240 км, Бокты тауының жанында."],
        ["Ең жақсы жарық — кешкісін, қабаттар айқынырақ көрінеді.", "2026 жылғы 1 қыркүйектен кіру ақылы."],
        []),
),
"beket_ata": _site(
  unesco=True,
  sources=[("Википедия — Мечеть Бекет-ата (Огланды)", W + "Мечеть_Бекет-ата_(Огланды)"),
           ("Википедия — Бекет-ата", W + "Бекет-ата"), UNESCO_SOURCE],
  terms=[("underground (rock-cut) mosque", "подземная (скальная) мечеть", "жерасты мешіті"),
         ("Sufi", "суфий", "сопы"), ("pilgrimage", "паломничество", "зиярат"), ("hermit", "отшельник", "ғұзлат, тақуа")],
  ru=_t("Скальная мечеть-пристанище суфия Бекета-аты в Огланды — главное место паломничества Мангистау, объект ЮНЕСКО.",
        ["Бекет-ата (Бекет Мырзагулулы) — суфий, просветитель и батыр; годы жизни условно 1750–1813.",
         "По преданию, в 14 лет он ночевал у захоронения Шопан-аты, и тот во сне направил его учиться в Хиву; там он 7 лет учился в медресе Шергази-хана.",
         "Мечеть вырублена в скале: пять округлых камер, в одной — михраб, в нише висят рога архара. Здесь Бекет-ата жил отшельником и здесь похоронен.",
         "Легенда о бое: Бекет обернулся лебедем, поднялся ветер, и 50 всадников показались врагу пятью сотнями. Он запретил убивать бегущих.",
         "В июле 2026 года мечеть вошла в список Всемирного наследия ЮНЕСКО в составе объекта «Скальные мечети Мангистау» — вместе с Шопан-атой, Караман-атой, Шакпак-атой и Султан-эпе."],
        ["Каракиянский район, 61 км на восток-северо-восток от посёлка Сенек, у западного чинка Устюрта. Автодорогу со стороны Актау проложили в 2010–2011 годах."],
        ["Логично ехать сначала к Шопан-ате: по преданию, именно там Бекет-ата получил благословение на путь.",
         "Предупредите группу о крутом спуске к мечети и о дресс-коде."],
        ["Закрытая одежда, женщинам — платок, внутри тишина. Паломников снимать только с разрешения."]),
  en=_t("The rock-cut hermitage mosque of the Sufi Beket Ata at Oglandy — Mangystau's main pilgrimage site and a UNESCO World Heritage component.",
        ["Beket Ata (Beket Myrzagululy) was a Sufi, educator and batyr; his life dates are conventionally 1750–1813.",
         "Legend says that at 14 he spent a night at the tomb of Shopan Ata, who in a dream sent him to study in Khiva, where he studied for 7 years at the Shergazi Khan madrasa.",
         "The mosque is cut into the rock: five rounded chambers, one with a mihrab and argali horns hanging in a niche. Beket Ata lived here as a hermit and is buried here.",
         "A battle legend: Beket turned into a swan, a wind rose, and 50 riders looked like 500 to the enemy. He forbade killing those who fled.",
         "In July 2026 the mosque was inscribed on the UNESCO World Heritage List as part of the “Rock Mosques of Mangystau”, together with Shopan Ata, Karaman Ata, Shakpak Ata and Sultan Epe."],
        ["Karakiya district, 61 km east-north-east of Senek, below the western escarpment of the Ustyurt. The road from Aktau was built in 2010–2011."],
        ["It makes sense to visit Shopan Ata first: by legend, that is where Beket Ata received his blessing.",
         "Warn the group about the steep descent to the mosque and the dress code."],
        ["Covered clothing, a headscarf for women, silence inside. Photograph pilgrims only with permission."]),
  kk=_t("Оғландыдағы сопы Бекет атаның жартастағы мешіт-мекені — Маңғыстаудың басты зиярат орны, ЮНЕСКО нысаны.",
        ["Бекет ата (Бекет Мырзағұлұлы) — сопы, ағартушы және батыр; өмір жылдары шартты түрде 1750–1813.",
         "Аңыз бойынша, ол 14 жасында Шопан ата басына түнеп, Шопан ата түсінде оны Хиуаға оқуға жіберген; ол онда Шерғазы хан медресесінде 7 жыл оқыған.",
         "Мешіт жартасқа қашалған: бес дөңгелек бөлме, бірінде михраб, қуыста арқар мүйізі ілулі. Бекет ата мұнда ғұзлатта өмір сүріп, осында жерленген.",
         "Шайқас туралы аңыз: Бекет аққуға айналып, жел тұрғанда 50 салт атты жауға бес жүздей көрінген. Ол қашқандарды өлтіруге тыйым салған.",
         "2026 жылғы шілдеде мешіт «Маңғыстаудың жартас мешіттері» нысанының құрамында Шопан ата, Қараман ата, Шақпақ ата және Сұлтан эпемен бірге ЮНЕСКО-ның Бүкіләлемдік мұра тізіміне енді."],
        ["Қарақия ауданы, Сенек кентінен шығыс-солтүстік-шығысқа қарай 61 км, Үстірттің батыс шыңы түбінде. Ақтау жақтан автожол 2010–2011 жылдары салынды."],
        ["Алдымен Шопан атаға барған жөн: аңыз бойынша Бекет ата жолына батаны дәл сол жерден алған.",
         "Топқа мешітке түсетін тік жол мен киім үлгісі туралы ескертіңіз."],
        ["Жабық киім, әйелдерге орамал, ішінде тыныштық. Зиярат етушілерді тек рұқсатпен суретке түсіріңіз."]),
),
"shopan_ata": _site(
  unesco=True,
  sources=[("welcome.kz — мечеть Шопан-ата", "https://welcome.kz/ru/info-cities/mangystau/shopan-ata-mosque"),
           ("Сакральные места Мангистау — Шопан ата", "https://mangystau.inmap.kz/ru/places/?title=nekropol_i_podzemnaya_mechet_shopan_ata_194&page=3"),
           UNESCO_SOURCE],
  terms=[("necropolis", "некрополь", "қорым"), ("disciple", "ученик", "шәкірт")],
  ru=_t("Подземная мечеть и крупнейший некрополь Мангистау — больше 3 000 захоронений; объект ЮНЕСКО.",
        ["Мечеть датируют примерно IX–XI веками; в ней 12 помещений разного назначения.",
         "Шопан-ата — суфий, живший в XII–XIII веках; по преданию — ученик Ходжи Ахмеда Ясави.",
         "По легенде, Ясави велел ученикам пустить стрелы через шанырак юрты — куда упадёт стрела, туда и идти.",
         "Некрополь — крупнейший в Мангистау, больше 3 000 захоронений.",
         "С июля 2026 — часть объекта Всемирного наследия ЮНЕСКО «Скальные мечети Мангистау»."],
        ["Каракиянский район, около 12 км на северо-восток от посёлка Сенек."],
        ["Логично ставить в маршрут перед Бекет-атой.", "Покажите разные эпохи надгробий на некрополе — это наглядная история."],
        ["Дресс-код и тишина, как в любой действующей святыне."]),
  en=_t("An underground mosque and the largest necropolis in Mangystau — over 3,000 burials; a UNESCO component.",
        ["The mosque is dated to about the 9th–11th centuries and has 12 rooms with different purposes.",
         "Shopan Ata was a Sufi who lived in the 12th–13th centuries; by tradition, a disciple of Khoja Ahmed Yasawi.",
         "Legend says Yasawi told his disciples to shoot arrows through the shanyrak of a yurt — wherever an arrow fell, that is where to go.",
         "The necropolis is the largest in Mangystau, with over 3,000 burials.",
         "Since July 2026 it is part of the UNESCO World Heritage property “Rock Mosques of Mangystau”."],
        ["Karakiya district, about 12 km north-east of Senek."],
        ["It makes sense to visit before Beket Ata.", "Show the different eras of gravestones in the necropolis — a vivid history lesson."],
        ["Dress code and silence, as at any active shrine."]),
  kk=_t("Жерасты мешіті және Маңғыстаудағы ең үлкен қорым — 3 000-нан астам жерлеу; ЮНЕСКО нысаны.",
        ["Мешіт шамамен IX–XI ғасырларға жатқызылады; онда түрлі мақсаттағы 12 бөлме бар.",
         "Шопан ата — XII–XIII ғасырларда өмір сүрген сопы; дәстүр бойынша Қожа Ахмет Ясауидің шәкірті.",
         "Аңыз бойынша, Ясауи шәкірттеріне киіз үйдің шаңырағы арқылы садақ атуды бұйырған — жебе қайда түссе, сонда бару керек.",
         "Қорым — Маңғыстаудағы ең үлкені, 3 000-нан астам жерлеу.",
         "2026 жылғы шілдеден — ЮНЕСКО-ның «Маңғыстаудың жартас мешіттері» Бүкіләлемдік мұра нысанының бөлігі."],
        ["Қарақия ауданы, Сенек кентінен солтүстік-шығысқа қарай шамамен 12 км."],
        ["Маршрутта Бекет атадан бұрын қою қисынды.", "Қорымдағы әр дәуірдің құлпытастарын көрсетіңіз — көрнекі тарих."],
        ["Кез келген киелі орындағыдай — киім үлгісі мен тыныштық."]),
),
"karaman_ata": _site(
  unesco=True,
  sources=[("Википедия — Караман-Ата", W + "Караман-Ата"), UNESCO_SOURCE],
  terms=[("necropolis", "некрополь", "қорым"), ("mausoleum", "мавзолей", "кесене"), ("skylight", "световой проём", "жарық саңылауы")],
  ru=_t("Один из самых ранних погребально-культовых комплексов Мангышлака: некрополь 7,2 га и подземная мечеть; объект ЮНЕСКО.",
        ["Самые древние надгробия датируют VIII–IX веками — огузо-кыпчакский период.",
         "Подземную мечеть, по мнению архитектора М. Мендикулова, начали строить в XII веке: вестибюль, молитвенный зал 23 × 6 м и круглое помещение, где, по легенде, похоронен Караман-ата.",
         "Потолок зала держат колонны, свет падает через два круглых проёма.",
         "На некрополе — расписные мавзолеи XIX века, например мавзолей Шоинбая; многие построили адайские мастера Омир Караулы и Назар Омирулы.",
         "По адайским преданиям, Караман-ата — внук (по другой версии — сын) Шопан-аты."],
        ["Мангистауский район."],
        ["Сравните туркменские и казахские надгробия в западной части некрополя — редкий пример соседства традиций."],
        ["Потолки в мечети низкие — предупредите высоких гостей."]),
  en=_t("One of the earliest burial and cult complexes of Mangyshlak: a 7.2-hectare necropolis and an underground mosque; a UNESCO component.",
        ["The oldest gravestones date from the 8th–9th centuries — the Oghuz-Kipchak period.",
         "According to architect M. Mendikulov, the underground mosque was begun in the 12th century: a vestibule, a 23 × 6 m prayer hall and a round room where, by legend, Karaman Ata is buried.",
         "Columns support the hall ceiling; light comes through two round openings.",
         "The necropolis has painted 19th-century mausoleums, such as the Shoinbay mausoleum; many were built by Adai masters Omir Karauly and Nazar Omiruly.",
         "By Adai tradition, Karaman Ata was the grandson (or son) of Shopan Ata."],
        ["Mangystau district."],
        ["Compare the Turkmen and Kazakh gravestones in the western part of the necropolis — a rare example of traditions side by side."],
        ["Ceilings in the mosque are low — warn tall guests."]),
  kk=_t("Маңғыстаудағы ең ерте жерлеу-ғибадат кешендерінің бірі: 7,2 га қорым және жерасты мешіті; ЮНЕСКО нысаны.",
        ["Ең көне құлпытастар VIII–IX ғасырларға — оғыз-қыпшақ кезеңіне жатады.",
         "Сәулетші М. Меңдіқұловтың пікірінше, жерасты мешітінің құрылысы XII ғасырда басталған: кіреберіс, 23 × 6 м намаз залы және аңыз бойынша Қараман ата жерленген дөңгелек бөлме.",
         "Зал төбесін бағандар ұстап тұр, жарық екі дөңгелек саңылау арқылы түседі.",
         "Қорымда XIX ғасырдың сырлы кесенелері бар, мысалы Шойынбай кесенесі; көбін адай шеберлері Өмір Қараулы мен Назар Өмірұлы салған.",
         "Адай аңыздары бойынша Қараман ата — Шопан атаның немересі (басқа нұсқа бойынша — ұлы)."],
        ["Маңғыстау ауданы."],
        ["Қорымның батыс бөлігіндегі түрікмен және қазақ құлпытастарын салыстырыңыз — дәстүрлердің қатар өмір сүруінің сирек мысалы."],
        ["Мешіттің төбесі аласа — бойы биік қонақтарға ескертіңіз."]),
),
"shakpak_ata": _site(
  unesco=True,
  sources=[("Orexca — мечеть Шакпак-ата", "https://www.orexca.com/rus/kazakhstan/mangystau/shakpak-ata.htm"),
           ("Карта культуры — Шакпак-Ата", "https://culturemap.kz/ru/object/podzemnaya-mechet-shakpak-ata-pamyatnik-arhitektury-h-hv"),
           UNESCO_SOURCE],
  terms=[("cross-shaped plan", "крестообразный план", "крест тәрізді жоспар"), ("inscription", "надпись", "жазу"),
         ("petroglyph / rock drawing", "наскальный рисунок", "жартас суреті")],
  ru=_t("Крестообразная скальная мечеть с надписями паломников с 1707 года; объект ЮНЕСКО.",
        ["В плане мечеть — крест, концы которого смотрят строго по сторонам света; четыре камеры, колонны с капителями.",
         "По архитектуре её относят к IX–X векам (оценки датировки в источниках расходятся).",
         "Единственный памятник Арало-Каспийского региона с надписями и рисунками на стенах: суфийские надписи, пометки паломников начиная с 1707–1708 годов, силуэты коней, всадников и ладоней.",
         "С июля 2026 — в составе объекта ЮНЕСКО. ЮНЕСКО рекомендовал пересмотреть использование цементного раствора при реставрации — отсюда слух, что мечеть «не включили». Это неверно."],
        ["Тупкараганский полуостров, более 20 км на северо-восток от Форт-Шевченко."],
        ["Покажите группе самые старые датированные надписи — туристы любят находить даты сами."],
        ["Надписи трогать нельзя — предупредите заранее."]),
  en=_t("A cross-shaped rock-cut mosque with pilgrim inscriptions dating back to 1707; a UNESCO component.",
        ["The mosque plan is a cross with its arms pointing exactly to the cardinal directions; four chambers, columns with capitals.",
         "Its architecture is attributed to the 9th–10th centuries (sources differ on dating).",
         "It is the only monument in the Aral-Caspian region with inscriptions and drawings on its walls: Sufi texts, pilgrim marks from 1707–1708 onwards, silhouettes of horses, riders and open palms.",
         "Part of the UNESCO property since July 2026. UNESCO recommended reassessing the cement mortar used in restoration — hence the rumour that it was “not included”. That is wrong."],
        ["Tupkaragan peninsula, over 20 km north-east of Fort-Shevchenko."],
        ["Show the oldest dated inscriptions — guests love spotting the dates themselves."],
        ["Inscriptions must not be touched — warn guests in advance."]),
  kk=_t("1707 жылдан бастап зиярат етушілердің жазулары бар крест тәрізді жартас мешіті; ЮНЕСКО нысаны.",
        ["Мешіттің жоспары — ұштары дүниенің төрт тарапына қатаң бағытталған крест; төрт бөлме, басы өрнектелген бағандар.",
         "Сәулеті бойынша IX–X ғасырларға жатқызылады (дереккөздерде мерзімі әртүрлі).",
         "Арал-Каспий өңіріндегі қабырғасында жазулары мен суреттері бар жалғыз ескерткіш: сопылық жазулар, 1707–1708 жылдардан бастап зиярат етушілердің белгілері, ат, салт атты және алақан бейнелері.",
         "2026 жылғы шілдеден — ЮНЕСКО нысанының құрамында. ЮНЕСКО қалпына келтіруде цемент ерітіндісін қолдануды қайта қарауды ұсынды — мешітті «енгізбеді» деген қауесет осыдан. Бұл дұрыс емес."],
        ["Түпқараған түбегі, Форт-Шевченкодан солтүстік-шығысқа қарай 20 км-ден астам."],
        ["Ең көне мерзімі бар жазуларды көрсетіңіз — туристер мерзімдерді өздері тапқанды ұнатады."],
        ["Жазуларды ұстауға болмайды — алдын ала ескертіңіз."]),
),
"sultan_epe": _site(
  unesco=True,
  sources=[("Википедия — Султан-эпе", W + "Султан-эпе"), UNESCO_SOURCE],
  terms=[("patron saint of sailors", "покровитель моряков", "теңізшілердің пірі"), ("shipwreck", "кораблекрушение", "кеме апаты")],
  ru=_t("Некрополь и подземная мечеть покровителя моряков; объект ЮНЕСКО.",
        ["Памятник X–XIX веков: некрополь и подземная мечеть.",
         "По преданию, Султан-эпе — младший сын суфия Гакима-аты, ученика Ходжи Ахмеда Ясави.",
         "Легенда: он опоздал на зов отца, потому что спасал людей с тонущих судов на Каспии, — и показал мокрую одежду и след верёвки на спине. С тех пор его почитают покровителем терпящих бедствие на море.",
         "С июля 2026 — часть объекта ЮНЕСКО «Скальные мечети Мангистау»."],
        ["Тупкараганский район, 57 км на северо-восток от Форт-Шевченко."],
        ["Для гостей из морских стран история о покровителе моряков — самая сильная на маршруте."],
        ["Дресс-код и тишина."]),
  en=_t("A necropolis and underground mosque of the patron saint of sailors; a UNESCO component.",
        ["A monument of the 10th–19th centuries: a necropolis and an underground mosque.",
         "By tradition, Sultan Epe was the youngest son of the Sufi Gakim Ata, a disciple of Khoja Ahmed Yasawi.",
         "Legend: he was late to his father's call because he was rescuing people from sinking ships on the Caspian — and showed his wet clothes and a rope mark on his back. Since then he has been revered as the patron of those in distress at sea.",
         "Since July 2026 part of the UNESCO property “Rock Mosques of Mangystau”."],
        ["Tupkaragan district, 57 km north-east of Fort-Shevchenko."],
        ["For guests from seafaring countries, the story of the sailors' patron is the strongest on the route."],
        ["Dress code and silence."]),
  kk=_t("Теңізшілер пірінің қорымы мен жерасты мешіті; ЮНЕСКО нысаны.",
        ["X–XIX ғасырлардың ескерткіші: қорым және жерасты мешіті.",
         "Дәстүр бойынша Сұлтан эпе — Қожа Ахмет Ясауидің шәкірті, сопы Хакім атаның кенже ұлы.",
         "Аңыз: ол әкесінің шақыруына кешігіп келген, өйткені Каспийде батып бара жатқан кемелердегі адамдарды құтқарған — дәлел ретінде су киімі мен арқасындағы арқан ізін көрсеткен. Содан бері оны теңізде апатқа ұшырағандардың пірі деп қастерлейді.",
         "2026 жылғы шілдеден — ЮНЕСКО-ның «Маңғыстаудың жартас мешіттері» нысанының бөлігі."],
        ["Түпқараған ауданы, Форт-Шевченкодан солтүстік-шығысқа қарай 57 км."],
        ["Теңізші елдерден келген қонақтар үшін теңізшілер пірі туралы әңгіме — маршруттағы ең әсерлісі."],
        ["Киім үлгісі мен тыныштық."]),
),
"karagiye": _site(
  sources=[("Википедия — Карагие", W + "Карагие")],
  terms=[("depression", "впадина", "ойыс"), ("below sea level", "ниже уровня моря", "теңіз деңгейінен төмен"),
         ("karst", "карст", "карст")],
  ru=_t("Впадина глубиной 132 метра ниже уровня моря — самая глубокая сухая впадина Казахстана.",
        ["Отметка дна — 132 м ниже уровня моря: одна из самых глубоких впадин Азии.",
         "Размеры — около 85 × 25 км.",
         "Название связывают с тюркским «кара кия» — «чёрный крутой склон»; по другой версии — «чёрная пасть». Второе название — Батыр.",
         "Впадина образовалась из-за выщелачивания солёных пород и карста — процессы идут и сейчас."],
        ["Около 50 км от Актау — самый близкий к городу «вау-объект»."],
        ["Хороший вариант на полдня, если у группы мало времени."],
        ["У края впадины крутые обрывы — держите группу подальше от кромки."]),
  en=_t("A depression 132 metres below sea level — the deepest dry depression in Kazakhstan.",
        ["The floor lies 132 m below sea level — one of the deepest depressions in Asia.",
         "It measures about 85 × 25 km.",
         "The name is linked to Turkic “kara kiya”, “black steep slope”; another version is “black maw”. Its second name is Batyr.",
         "It formed through leaching of salt rocks and karst — processes that continue today."],
        ["About 50 km from Aktau — the closest “wow” site to the city."],
        ["A good half-day option when the group is short on time."],
        ["The edges are steep cliffs — keep the group away from the rim."]),
  kk=_t("Теңіз деңгейінен 132 метр төмен ойыс — Қазақстандағы ең терең құрғақ ойыс.",
        ["Түбі теңіз деңгейінен 132 м төмен: Азиядағы ең терең ойыстардың бірі.",
         "Өлшемі — шамамен 85 × 25 км.",
         "Атауы түркінің «қара қия» — «қара тік беткей» сөзімен байланыстырылады; басқа нұсқа — «қара ауыз». Екінші атауы — Батыр.",
         "Ойыс тұзды жыныстардың шайылуы мен карст салдарынан пайда болған — бұл процестер қазір де жүріп жатыр."],
        ["Ақтаудан шамамен 50 км — қалаға ең жақын әсерлі нысан."],
        ["Топтың уақыты аз болса — жарты күндік жақсы нұсқа."],
        ["Ойыстың шетінде тік жарлар — топты жиектен алыс ұстаңыз."]),
),
"zhygylgan": _site(
  sources=[("Orexca — Жыгылган", "https://www.orexca.com/rus/kazakhstan/mangystau/zhygylgan.htm"),
           ("Advantour — Zhygylgan", "https://www.advantour.com/kazakhstan/mangystau/zhygylgan.htm")],
  terms=[("landslide / collapse", "обвал, провал", "опырылу"), ("fossil footprints", "окаменелые следы", "тасқа айналған іздер")],
  ru=_t("«Упавшая земля»: обрушившийся пласт 2 × 4 км с окаменелыми следами древних животных.",
        ["Название в переводе с казахского — «упавшая земля».",
         "Пласт породы толщиной до 50 метров и размером около 2 × 4 км рухнул в пустоты и раскололся на тысячи глыб.",
         "На осколках можно найти окаменелые следы животных возрастом около 10–15 миллионов лет."],
        ["Тупкараганский район."],
        ["Искать следы вместе с группой — лучший интерактив; покажите, как их отличить от трещин."],
        ["Глыбы неустойчивы — не разрешайте прыгать по краям."]),
  en=_t("“Fallen land”: a collapsed 2 × 4 km slab with fossil footprints of ancient animals.",
        ["The Kazakh name means “fallen land”.",
         "A rock slab up to 50 m thick and about 2 × 4 km collapsed into voids and broke into thousands of blocks.",
         "Fossil animal footprints about 10–15 million years old can be found on the fragments."],
        ["Tupkaragan district."],
        ["Searching for footprints together is the best group activity; show how to tell them from cracks."],
        ["The blocks are unstable — do not let guests jump along the edges."]),
  kk=_t("«Жығылған жер»: ежелгі жануарлардың тасқа айналған іздері бар 2 × 4 км опырылған қабат.",
        ["Атауы қазақша «жығылған жер» дегенді білдіреді.",
         "Қалыңдығы 50 метрге дейінгі, шамамен 2 × 4 км тау жынысы қабаты қуыстарға опырылып, мыңдаған кесекке бөлінген.",
         "Сынықтардан жасы шамамен 10–15 миллион жыл болатын жануарлардың тасқа айналған іздерін табуға болады."],
        ["Түпқараған ауданы."],
        ["Іздерді топпен бірге іздеу — ең жақсы белсенділік; оларды жарықшақтардан қалай ажыратуды көрсетіңіз."],
        ["Кесектер орнықсыз — шеттерімен секіруге рұқсат бермеңіз."]),
),
"kapamsay": _site(
  draft=True, sources=[],
  terms=[("chalk canyon", "меловой каньон", "бор шатқалы")],
  ru=_t("Белый меловой каньон на Тупкарагане.", [], ["Тупкараганский район, рядом с Жыгылганом."], [], []),
  en=_t("A white chalk canyon on the Tupkaragan peninsula.", [], ["Tupkaragan district, near Zhygylgan."], [], []),
  kk=_t("Түпқарағандағы ақ бор шатқалы.", [], ["Түпқараған ауданы, Жығылғанның жанында."], [], []),
),
"kenderli": _site(
  draft=True, sources=[("AstanaTV — курортная зона Кендерли, 09.06.2026", "https://astanatv.kz/ru/news/170364/")],
  terms=[("resort area", "курортная зона", "курорттық аймақ"), ("bay", "залив", "шығанақ")],
  ru=_t("Курортная зона на побережье Каспия у залива Кендерли.", [],
        ["Подчиняется администрации Жанаозена. В 2026 году рядом строится аэропорт Кендерли (техническая готовность около 35% на июнь 2026)."], [], []),
  en=_t("A resort area on the Caspian coast by Kenderli Bay.", [],
        ["Administered by Zhanaozen. An airport is being built nearby in 2026 (about 35% technically complete as of June 2026)."], [], []),
  kk=_t("Каспий жағалауындағы Кендірлі шығанағындағы курорттық аймақ.", [],
        ["Жаңаөзен әкімдігіне бағынады. 2026 жылы жанында Кендірлі әуежайы салынып жатыр (2026 жылғы маусымда техникалық дайындығы шамамен 35%)."], [], []),
),
}


def site_content(slug: str, lang: str) -> dict | None:
    s = SITES.get(slug)
    if not s:
        return None
    return {**s[lang], "unesco": s["unesco"], "fee": s["fee"], "sources": s["sources"],
            "terms": s["terms"], "draft": s["draft"]}


# Опасная фауна и первая помощь. Только проверенное; не заменяет медицинскую помощь.
FAUNA_SOURCES = [
    ("lada.kz — в Мангистау 8 видов змей, ядовит только щитомордник",
     "https://www.lada.kz/society/society/58241-taktika-nenapadeniya-v-mangistau-obitayut-vosem-vidov-zmey.html"),
    ("lada.kz — опасные членистоногие Мангистау (к.б.н. М. Пестов, 2024)",
     "https://www.lada.kz/society/society/121068-opasnye-chlenistonogie-mangistau-s-kem-luchshe-ne-vstrechatsya.html"),
    ("lada.kz — укусы каракурта и нехватка сыворотки, 15.06.2026",
     "https://www.lada.kz/aktau_news/society/154336-v-mangistau-nashestvie-karakurtov-v-bolnitsakh-otmechaetsia-nedostatochnyi-zapas-protivoiadiia.html"),
    ("factcheck.kz — стоит ли прижигать укус каракурта (врач-токсиколог)",
     "https://factcheck.kz/fastchesk/stoit-li-prizhigat-mesto-ukusa-karakurta/"),
    ("WHO — Snakebite envenoming", "https://www.who.int/health-topics/snakebite"),
]

FAUNA = {
"ru": {
 "species": [
  ("Каракурт", "Самый опасный: яд опасен для жизни, лечение — специальная сыворотка. Живёт в песке, у камней, в сухой траве и заброшенных постройках; пик — июль–сентябрь. В 2026 году к середине июня в Мангистау было 18 обращений с укусами, а сыворотки в части больниц не хватало."),
  ("Обыкновенный щитомордник", "Из 8 видов змей Мангистау ядовит только он. Случаев смерти от укуса змей в регионе не зарегистрировано, но к врачу — обязательно."),
  ("Скорпион", "Болезненный укус, отёк, возбуждение нервной системы."),
  ("Тарантул", "Покраснение, отёк, онемение, сыпь."),
  ("Фаланга (сольпуга)", "Ядовитых желёз нет, но челюсти крепкие — укус нужно обработать антисептиком."),
  ("Иксодовые клещи", "Переносят опасные заболевания — осматривайте одежду и кожу после прогулок."),
 ],
 "camp": [
  "Ставьте лагерь засветло и осмотрите место: норы, трещины, камни.",
  "Держите палатки закрытыми, вещи — внутри.",
  "Утром вытряхивайте обувь и одежду.",
  "Каракурта не трогайте, не подходите и не снимайте вблизи — спокойно отойдите.",
 ],
 "aid": [
  ("Укус каракурта",
   ["Промойте место укуса чистой водой, наложите стерильную повязку, приложите холод.",
    "Покой. Звоните 103 или 112 и везите в больницу — лечит только сыворотка.",
    "Заранее позвоните в больницу и уточните, есть ли сыворотка."],
   ["Не прижигайте: по словам врача-токсиколога, это не нейтрализует яд и добавляет ожог."]),
  ("Укус змеи",
   ["Успокойте пострадавшего, уложите, обездвижьте укушенную конечность.",
    "Снимите кольца, часы, браслеты — начнётся отёк.",
    "Срочно в больницу, звоните 103 или 112."],
   ["Нельзя: жгут, разрезы, отсасывание яда, прижигание и народные средства — по данным ВОЗ, они вредят."]),
  ("Скорпион, тарантул, фаланга",
   ["Обработайте место укуса антисептиком, приложите холод.",
    "Сильная боль, отёк или плохое самочувствие — к врачу."],
   []),
 ],
 "kit": ["Бинты и стерильные салфетки", "Антисептик", "Эластичный бинт и шина для фиксации", "Термоодеяло",
         "Холодный пакет", "Запас воды", "Фонарь",
         "Личные лекарства и EpiPen — у туриста: спросите заранее через анкету безопасности"],
},
"en": {
 "species": [
  ("Karakurt", "The most dangerous: its venom is life-threatening and treated with a specific antivenom. Lives in sand, near rocks, in dry grass and abandoned buildings; peak season July–September. By mid-June 2026 Mangystau had 18 bite cases, and some hospitals were short of antivenom."),
  ("Halys pit viper", "The only venomous one of Mangystau's 8 snake species. No snakebite deaths have been recorded in the region, but a doctor is still a must."),
  ("Scorpion", "Painful sting, swelling, nervous agitation."),
  ("Tarantula", "Redness, swelling, numbness, rash."),
  ("Camel spider (solpugid)", "No venom glands, but strong jaws — disinfect the bite."),
  ("Ixodid ticks", "Carry dangerous diseases — check clothes and skin after walks."),
 ],
 "camp": [
  "Set up camp in daylight and inspect the spot: burrows, cracks, rocks.",
  "Keep tents closed and belongings inside.",
  "Shake out shoes and clothes in the morning.",
  "Do not touch, approach or photograph a karakurt up close — calmly move away.",
 ],
 "aid": [
  ("Karakurt bite",
   ["Rinse the bite with clean water, apply a sterile dressing and a cold compress.",
    "Keep the person still. Call 103 or 112 and go to hospital — only antivenom treats it.",
    "Call the hospital ahead to check that antivenom is available."],
   ["Do not cauterize: according to a toxicologist, it does not neutralize the venom and adds a burn."]),
  ("Snakebite",
   ["Reassure the person, lay them down, immobilize the bitten limb.",
    "Remove rings, watches, bracelets — swelling will follow.",
    "Go to hospital urgently, call 103 or 112."],
   ["Never: tourniquets, cuts, sucking out venom, cauterizing or folk remedies — WHO says they do harm."]),
  ("Scorpion, tarantula, camel spider",
   ["Disinfect the bite and apply cold.",
    "Severe pain, swelling or feeling unwell — see a doctor."],
   []),
 ],
 "kit": ["Bandages and sterile wipes", "Antiseptic", "Elastic bandage and splint", "Thermal blanket",
         "Cold pack", "Water supply", "Flashlight",
         "Personal medicines and EpiPens stay with the traveler — ask in advance via the safety form"],
},
"kk": {
 "species": [
  ("Қарақұрт", "Ең қауіптісі: уы өмірге қауіпті, тек арнайы сарысумен емделеді. Құмда, тас жанында, құрғақ шөпте және тастанды ғимараттарда тіршілік етеді; шыңы — шілде–қыркүйек. 2026 жылғы маусымның ортасына дейін Маңғыстауда шағудан 18 адам жүгінді, ал кейбір ауруханаларда сарысу жетіспеді."),
  ("Кәдімгі қалқантұмсық", "Маңғыстаудағы 8 жылан түрінің ішінде тек осы улы. Өңірде жылан шағып өлу жағдайы тіркелмеген, бірақ дәрігерге бару міндетті."),
  ("Шаян", "Ауырсынатын шағу, ісік, жүйке қозуы."),
  ("Бүйі (тарантул)", "Қызару, ісік, ұю, бөртпе."),
  ("Фаланга (сольпуга)", "Улы бездері жоқ, бірақ жақтары мықты — шаққан жерді антисептикпен өңдеу керек."),
  ("Иксод кенелері", "Қауіпті аурулар таратады — серуеннен кейін киім мен теріні тексеріңіз."),
 ],
 "camp": [
  "Лагерьді жарықта тігіп, орынды тексеріңіз: індер, жарықшақтар, тастар.",
  "Шатырларды жабық, заттарды ішінде ұстаңыз.",
  "Таңертең аяқ киім мен киімді қағыңыз.",
  "Қарақұртты ұстамаңыз, жақындамаңыз, жақыннан суретке түсірмеңіз — сабырмен алыстаңыз.",
 ],
 "aid": [
  ("Қарақұрт шақса",
   ["Шаққан жерді таза сумен жуып, стерильді таңғыш салып, суық басыңыз.",
    "Тыныштық. 103 немесе 112-ге қоңырау шалып, ауруханаға апарыңыз — тек сарысу емдейді.",
    "Ауруханаға алдын ала хабарласып, сарысу бар-жоғын біліңіз."],
   ["Күйдірмеңіз: токсиколог дәрігердің айтуынша, бұл уды бейтараптандырмайды, тек күйік қосады."]),
  ("Жылан шақса",
   ["Зардап шеккенді тыныштандырып, жатқызып, шағылған аяқ-қолды қозғалтпаңыз.",
    "Жүзік, сағат, білезікті шешіңіз — ісік басталады.",
    "Шұғыл ауруханаға, 103 немесе 112-ге қоңырау шалыңыз."],
   ["Болмайды: бұрау, кесу, уды сору, күйдіру және халықтық әдістер — ДДҰ деректері бойынша олар зиян."]),
  ("Шаян, бүйі, фаланга",
   ["Шаққан жерді антисептикпен өңдеп, суық басыңыз.",
    "Қатты ауырсыну, ісік немесе жағдай нашарласа — дәрігерге."],
   []),
 ],
 "kit": ["Таңғыштар мен стерильді майлықтар", "Антисептик", "Серпімді таңғыш және бекіткіш шина", "Термокөрпе",
         "Суық пакет", "Су қоры", "Қалта шам",
         "Жеке дәрілер мен EpiPen — туристте: қауіпсіздік сауалнамасы арқылы алдын ала сұраңыз"],
},
}


# Подтверждённые инциденты 2026 года — слой на карте маршрута.
INCIDENTS = [
    {"site": "tuzbair", "date": "31.05.2026",
     "ru": "Машина с семьёй туристов из Великобритании (двое взрослых и ребёнок) застряла в солончаке — спасатели вытаскивали её больше суток.",
     "en": "A car with a UK tourist family (two adults and a child) got stuck in the salt flat — rescuers worked for over a day to pull it out.",
     "kk": "Ұлыбританиядан келген турист отбасы (екі ересек және бала) мінген көлік сорға батып қалды — құтқарушылар оны бір тәуліктен астам шығарды.",
     "source": "https://www.zakon.kz/proisshestviia/6519771-britanskie-turisty-okazalis-v-lovushke-v-stepi-mangistau.html"},
    {"site": "bozjyra", "date": "02.2026",
     "ru": "Ночью в урочище в грязи застряла машина с 6 туристами (110 км от Жанаозена) — отбуксировали спасатели.",
     "en": "At night a car with 6 tourists got stuck in mud in the valley (110 km from Zhanaozen) — towed out by rescuers.",
     "kk": "Түнде шатқалда 6 турист мінген көлік балшыққа батты (Жаңаөзеннен 110 км) — құтқарушылар сүйреп шығарды.",
     "source": "https://inbusiness.kz/ru/last/turisty-zastryali-v-gryazi-v-gorah-mangistau"},
    {"site": "bozjyra", "date": "27.04.2026",
     "ru": "Два туристических автобуса (около 50 человек) застряли в грязи на полевой дороге — отбуксировали спасатели.",
     "en": "Two tour buses (about 50 people) got stuck in mud on a dirt road — towed out by rescuers.",
     "kk": "Екі туристік автобус (шамамен 50 адам) далалық жолда балшыққа батты — құтқарушылар сүйреп шығарды.",
     "source": "https://www.inform.kz/ru/spasateli-vitashili-dva-avtobusa-s-turistami-iz-gryazi-u-bozzhiri-32d98d"},
]
